# Generated by Django 4.2.3 on 2023-07-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depoimento', models.TextField(max_length=256)),
                ('nome_da_pessoa', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=50)),
            ],
        ),
    ]
