# Generated by Django 4.2.3 on 2023-08-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_destinos'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinos',
            name='foto_2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinos',
            name='meta',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinos',
            name='texto_descritivo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
