# Generated by Django 4.2.3 on 2023-08-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_destinos_foto_2_destinos_meta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinos',
            old_name='foto',
            new_name='Foto 1',
        ),
    ]
