# Generated by Django 4.2.3 on 2023-08-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_rename_foto_destinos_foto_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinos',
            old_name='Foto 1',
            new_name='foto',
        ),
    ]
