# Generated by Django 4.2.3 on 2023-08-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_rename_foto_1_destinos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinos',
            name='foto',
            field=models.CharField(max_length=50, verbose_name='Foto 1'),
        ),
    ]
